import redis

client = redis.Redis(host='127.0.0.1', port=31337)
client.set(1, 1)
client.set(2, 2)
print(client.get(1))
print(client.get(2))
client.delete(1)
print(client.get(1))
client.set('puchkin1', 1)
client.set('pushkin2', 2)
print(client.keys('pushkin'))
client.flushdb()
client.set('puchkin1', 1)
client.set('pushkin2', 2)
client.expire('pushkin2', 5)
client.hset('1', '2', '3')
print(client.hget('1', '2'))
client.rpush('my_list', 'one')
client.rpush('my_list', 'two')
client.rpush('my_list', 'three')
client.lpush('my_list', 'null')
client.lset('my_list', 2, 'five')
print(client.lrange('my_list', 0, -1))
print(client.lindex('my_list', 2))
